---
- name: DotFiles Config
  hosts: localhost
  connection: local
  
  pre_tasks:
    - name: pre-task | Detect WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags:
        - always

    - name: pre-task | Detect wsl
      ansible.builtin.debug:
        var: ansible_host_environment_is_wsl
      tags:
        - always

    - name: pre-task | Confirm Windows PowerShell Execution Policy
      ansible.builtin.import_tasks: pre_tasks/powershell_executionpolicy.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: pre-task | Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami_wsl.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: pre-task | Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

    - name: pre-task | Detect LastPass
      ansible.builtin.import_tasks: pre_tasks/detect_lastpass.yml
      tags:
        - always

  tasks:
    - name: pre-task | Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or (['system'] + (default_roles | difference(exclude_roles | default([])))) | sort }}"
      tags:
        - always

    - name: pre-task | Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
