---
- name: "SSH | Get [{{ item.name }}] private key from LastPass"
  ansible.builtin.command: "lpass show --notes '{{ item.vault_path }}' --field='Private Key'"
  register: lp_private_key
  changed_when: false
  no_log: true

- name: "SSH | Get [{{ item.name }}] public key from LastPass"
  ansible.builtin.command: "lpass show --notes '{{ item.vault_path }}' --field='Public Key'"
  register: lp_public_key
  changed_when: false
  no_log: true

- name: "SSH | Copy SSH keys"
  block:
    - name: "SSH | Deploy [{{ item.name }}] private key"
      ansible.builtin.copy:
        dest: "{{ ansible_user_dir }}/.ssh/{{ item.name }}"
        content: "{{ lp_private_key.stdout }}\n"
        mode: "0600"
      no_log: true

    - name: "SSH | Deploy [{{ item.name }}] public key"
      ansible.builtin.copy:
        dest: "{{ ansible_user_dir }}/.ssh/{{ item.name }}.pub"
        content: "{{ lp_public_key.stdout }}"
        mode: "0644"
      no_log: true
