---
- name: "Zsh | Arch | Install"
  ansible.builtin.pacman:
    name: zsh
    state: present
  become: true

- name: "Zsh | Set default shell"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /usr/bin/zsh
  become: true
