---
- name: "zsh | ArchLinux | Install zsh"
  ansible.builtin.pacman:
    name: zsh
    state: present
  become: true

- name: "zsh | ArchLinux | Set zsh as default shell"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /usr/bin/zsh
  become: true
