---
- name: sgpt | ArchLinux | Get latest sgpt release
  uri:
    url: "https://api.github.com/repos/tbckr/sgpt/releases/latest"
    return_content: yes
  register: sgpt_release

- name: sgpt | ArchLinux | Set latest version of sgpt
  set_fact:
    sgpt_latest_version: "{{ sgpt_release.json.tag_name }}"

- name: sgpt | ArchLinux | Download sgpt .tar.gz for Linux x86_64
  get_url:
    url: "https://github.com/tbckr/sgpt/releases/download/{{ sgpt_latest_version }}/sgpt_{{ sgpt_latest_version[1:] }}_linux_x86_64.tar.gz"
    dest: "/tmp/sgpt.tar.gz"
    mode: '0644'

- name: sgpt | ArchLinux | Extract sgpt binary
  unarchive:
    src: "/tmp/sgpt.tar.gz"
    dest: "/tmp/sgpt"
    remote_src: yes

- name: sgpt | ArchLinux | Install sgpt binary to /usr/local/bin
  copy:
    src: "/tmp/sgpt/sgpt"
    dest: "/usr/local/bin/sgpt"
    mode: '0755'
    remote_src: yes
