---
- name: sgpt | ArchLinux | Get latest sgpt release
  uri:
    url: "https://api.github.com/repos/tbckr/sgpt/releases/latest"
    return_content: yes
  register: sgpt_release

- name: sgpt | ArchLinux | Set latest version of sgpt
  set_fact:
    sgpt_latest_version: "{{ sgpt_release.json.tag_name }}"

- name: sgpt | ArchLinux | Download sgpt .tar.gz for Linux x86_64
  get_url:
    url: "https://github.com/tbckr/sgpt/releases/download/{{ sgpt_latest_version }}/sgpt-{{ sgpt_latest_version[1:] }}-1-x86_64.pkg.tar.zst"
    dest: "/tmp/sgpt.pkg.tar.zst"
    mode: '0644'

- name: sgpt | ArchLinux | Install sgpt with pacman
  become: true
  pacman:
    name: "/tmp/sgpt.pkg.tar.zst"
    state: present