---
- name: "{{ role_name }} | Cleanup lazygit downloaded tar"
  ansible.builtin.file:
    path: "/tmp/{{ lazygit_file }}.tar.gz"
    state: absent
  become: true

- name: "{{ role_name }} | Remove extracted lazygit directory"
  ansible.builtin.file:
    path: /tmp/lazygit
    state: absent
  become: true

