---
# - name: "OrbStack | MacOSX | Detecting CPU [Apple Silicon or Intal]"
#   ansible.builtin.command: "sysctl -n machdep.cpu.brand_string"
#   changed_when: false
#   register: cpu_arch
#
# - name: "OrbStack | MacOSX | Calculating CPU Architecture"
#   ansible.builtin.set_fact:
#     cpu_arch: "{% if 'Apple' in cpu_arch.stdout %}apple{% else %}intel{% endif %}"
#
# - name: "OrbStack | MacOSK | Calculating Homebrew Cask Version"
#   ansible.builtin.set_fact:
#     homebrew_cask_version: "{% if cpu_arch == 'apple' %}{% else %}@1.5.1{% endif %}"

# - name: "OrbStack | MacOSX | Install OrbStack"
#   ansible.builtin.homebrew_cask:
#     name: "orbstack{{ homebrew_cask_version }}"
#     state: present

- name: "OrbStack | MacOSX | Install OrbStack"
  community.general.homebrew_cask:
    name: orbstack
    state: present
