---
- name: alacritty | ArchLinux | Install Alacritty
  community.general.pacman:
    name: alacritty
    state: present

- name: alacritty | ArchLinux | Ensure Alacritty config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    state: directory
    mode: '0755'

- name: alacritty | ArchLinux | Copy Alacritty configuration file
  copy:
    src: files/Archlinux_alacritty.yaml
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
    owner: "{{ ansible_env.USER }}"
    mode: '0644'
