---
- name: alacritty | WSL | Install Alacritty
  ansible.builtin.include_role:
    name: winget
  vars:
    winget_packages:
      - Alacritty.Alacritty

- name: alacritty | WSL | Copy Alacritty config into Windows
  block:
    - name: alacritty | WSL | Check to see if AppData\Roaming\alacritty exists
      ansible.builtin.stat:
        path: /mnt/c/Users/{{ wsl_host_user }}/AppData/Roaming/alacritty
      register: alacritty_dir

    - name: alacritty | WSL | Ensure AppData\Roaming\alacritty exists
      ansible.builtin.shell:
        cmd: New-Item -ItemType Directory -Path "$env:APPDATA\alacritty" -ErrorAction SilentlyContinue
      failed_when: false
      args:
        executable: powershell.exe
      when: alacritty_dir.stat.exists == false

    - name: alacritty | WSL | Copy Alacritty config
      ansible.builtin.copy:
        src: wsl_alacritty.yaml
        dest: /mnt/c/Users/{{ wsl_host_user }}/AppData/Roaming/alacritty/alacritty.yml
